config/routes.rb
ThriveMarket::Application.routes.draw do

  root 'static_pages#home'

  get  "/home"               => "static_pages#home",     as: :home
  post "/phone_numbers"      => "phone_numbers#create"
  post  "webhooks/sms"       => 'webhooks#incoming_text'
  get  "/thanks"             => "static_pages#thanks",   as: :thanks
  post "survey_items/create" => 'survey_items#create',   as: :survey_items

  get    "admin/signin"  => "sessions#new",     as: :sign_in
  delete "admin/signout" => 'sessions#destroy', as: :sign_out

  resources :sessions, only: [ :create ]
  resources :updates,  only: [ :create, :destroy ]

  get "admin"               => "admin#index",         as: :admin
  get "admin/survey_items"  => "admin#survey_items",  as: :admin_survey_items
  get "admin/phone_numbers" => "admin#phone_numbers", as: :admin_phone_numbers
  get "admin/updates"       => "admin#updates",       as: :admin_updates

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @phone_number = PhoneNumber.new
    @survey_item = SurveyItem.new
    session[:survey_seen] = Time.now
  end

  def thanks
    redirect_to root_url, notice: "Thank you, we will get back to you as soon as possible."
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_contact.html.erb
<div class="section about dashed-border black", id="contact">
  <div class="row">
    <div class="medium-12 columns">
      <h3 class="center white">Do you have questions, suggestions, or feedback?</h3>
      <div class="form-wrapper">
        <%= form_tag "http://formspree.io/info@thrivemarket.org", :"data-abide" => "" do %>
        <div class="row">
          <div class="medium-4 medium-offset-2 small-11 small-centered columns">
            <!--[if IE]>
            <%= label_tag :email %>
            <![endif]-->
            <div class="input-wrapper">
              <%= email_field_tag :email, nil, placeholder: "Email", name: "_replyto", required: true, pattern: "email" %>
              <small class="error">A valid email address is required.</small>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="medium-8 medium-centered small-11 small-centered columns">
            <!--[if IE]>
            <%= label_tag "Your Message" %>
            <![endif]-->
            <div class="input-wrapper">
              <%= text_area_tag :content, nil, placeholder: "Enter your message here", rows: 4, name: "content", required: true %>
              <small class="error">You must provide a message</small>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="medium-4 medium-offset-2 large-3 small-11 small-centered columns">
            <input type="hidden" name="_next" value="//www.thrivemarket.org<%= thanks_path %>" />
            <%= submit_tag "SEND MESSAGE", class: "button learn-more radius expand" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_survey.html.erb
<div id="myModal" class="reveal-modal" data-reveal>
  <div class="medium-8 medium-centered columns">
    <h3>Is there something you would like to see us grow in our garden?</h3>
    <p>
      It getting close to that time of the year where we will start planting our garden. Tell us what you would like to see planted.
    </p>
    <%= form_for @survey_item do |f| %>
      <%= f.label :message do %>
        What would you like to see grown in our garden?
      <% end %>
      <%= f.text_area :message, rows: 3 %>
      <%= f.submit "SEND FEEDBACK", class: "button learn-more survey_button" %>
    <% end %>
  </div>


  <a class="close-reveal-modal"><%= fa_icon "times-circle" %> CLOSE</a>
</div>

app/views/static_pages/home.html.erb
<%#= render 'static_pages/survey' %>

<div class="home-image f-topbar-fixed">
  <div data-alert class="alert-box orange">
    Want to help out with the garden? <%= link_to "Learn more", "#help", class: "smooth" %> about our weekly garden hangouts.
    <a href="#" class="close">&times;</a>
  </div>
  <div class="row">
    <div class="medium-12 columns">
      <%= render 'layouts/messages' %>
      <div class="logo-wrapper">
        <%= image_tag "logo.svg", alt: "Thrive Logo", class: "logo" %>
      </div>
      <h2 class="uvp">Cultivating community by growing affordable local produce and sharing ideas for healthy living.</h2>
      <%= link_to "Learn More", "#about", class: "button radius learn-more smooth" %>
    </div>
  </div>
</div>
<div class="section black about dashed-border", id="about">
  <div class="row">
    <div class="medium-5 columns center" id='cultivating_icon'></div>
    <div class="medium-7 columns">
      <h3 class="white">Helping our neighbors</h3>
      <p class="white">
        The Thrive Neighborhood Market & Community Garden provides affordable fresh produce to our community through our monthly farmers markets and community garden located at St. Paul's Episcopal Church, 900 Normal Rd, in DeKalb, IL.
        <br>
        <%= link_to "https://www.google.com/maps/preview?q=900+Normal+Road,+DeKalb,+IL&hl=en&sll=41.928177,-88.746305&sspn=0.226052,0.528374&oq=900+Normal+Road&hnear=900+Normal+Rd,+DeKalb,+Illinois+60115&t=m&z=17", target: "new" do %>
          <%= fa_icon "map-marker" %> Do you need directions?
        <% end %>
      </p>
      <div class="arrow-down">
        <%= link_to "#community", class: "smooth arrow-down" do %>
          <span class="fa-stack fa-2x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-angle-down fa-stack-1x"></i>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="section about dashed-border", id="community">
  <div class="row">
    <div class="medium-5 medium-push-7 columns center" id='community_icon'></div>
    <div class="medium-7 medium pull-5 columns">
      <h3>Community supported</h3>
      <p>
        This mission is supported by partnerships with St. Paul's Episcopal Church, DeKalb County Community Gardens, and volunteers in the NIU and DeKalb communities.
        Please <%= link_to "contact us", '#contact', class: "smooth" %> if you are interested in volunteering or supporting this cause.
      </p>
      <div class="arrow-down">
        <%= link_to "#healthy", class: "smooth arrow-down" do %>
          <span class="fa-stack fa-2x">
            <i class="fa fa-circle white-bg fa-stack-2x"></i>
            <i class="fa fa-angle-down fa-stack-1x"></i>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="section black about", id="healthy">
  <div class="row">
    <div class="medium-5 columns center" id='healthy_icon'></div>
    <div class="medium-7 columns">
      <h3 class="white">Promoting healthy living</h3>
      <p class="white">
        We are promoting healthy living in our community by sharing recipe ides and cooking methods.
        <%= link_to "Check out our blog", "http://thrivemarket.tumblr.com/" %> to see what is in season, or what will be available at our next market day.
      </p>
      <div class="arrow-down">
        <%= link_to "#when", class: "smooth arrow-down" do %>
          <span class="fa-stack fa-2x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-angle-down fa-stack-1x"></i>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="section about dashed-border", id="when">
  <div class="row">
    <div class="large-12 small-8 small-centered medium-8 medium-centered columns center">
      <h3 class="center">Market Dates</h3>
      <!-- <h5 class="center">
        Our market dates for 2016 are still to be determined.<br/>Please sign up for SMS updates to be notified when we have released our schedule.
      </h5>
      <br/> -->
      <h5 class="center">
        Join us at <%= link_to "St. Paul's Episcopal Church", "http://stpaulsdekalb.org/" %> on the following Saturdays:
      </h5>
      <div class="dates">
        <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-3">
          <!-- <li>
            <div class="date-card">
              <div class="month radius">
                <p>June</p>
              </div>
              <div class="day">
                <p>TBD</p>
                <small>11AM - 2PM</small>
              </div>
            </div>
          </li> -->
          <li>
            <div class="date-card">
              <div class="month radius">
                <p>July</p>
              </div>
              <div class="day">
                <p>16</p>
                <small>11AM - 2PM</small>
              </div>
            </div>
          </li>
          <li>
            <div class="date-card">
              <div class="month radius">
                <p>Aug</p>
              </div>
              <div class="day">
                <p>20</p>
                <small>11AM - 2PM</small>
              </div>
            </div>
          </li>
          <li>
            <div class="date-card">
              <div class="month radius">
                <p>Sept</p>
              </div>
              <div class="day">
                <p>17</p>
                <small>11AM - 2PM</small>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="medium-10 medium-centered columns">
      <h3 class="center">Enter your phone number to receive SMS updates</h3>
      <div class="form-wrapper phone-wrapper">
        <%= form_for @phone_number, html: { :"data-abide" => "" } do |f| %>
          <div class="row">
            <div class="medium-7 columns">
              <div class="input-wrapper">
                <%= f.telephone_field :number, placeholder: "123-456-7890", pattern: "phone", class: "large-font", required: true %>
                <small class="error">A valid phone number is required.</small>
              </div>
            </div>
            <div class="medium-5 small-12 columns end">
              <%= f.submit "SIGN UP", class: "button learn-more radius expand" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="section about black dashed-border" id="help">
  <div class="row">
    <div class="medium-12 columns">
      <h3 class="center white">Hangout with us on Tuesday evenings 6:30-7:30PM</h3>
      <!-- <p class="center white">Starting around mid-May, we invite you to stop out to the garden for fun, fellowship, and gardening.  We have a great mix of experienced gardeners and others who wouldn't exactly consider themselves a "green thumb" working and learning together.  Feel free to stop by if you would like to help.</p> -->

      <p class="center white">Each Tuesday evening we get together for some fun, fellowship, and gardening.  We have a great mix of experienced gardeners and others who wouldn't exactly consider themselves a "green thumb" working and learning together.  Feel free to stop by if you would like to help.</p>
    </div>
  </div>
</div>
<div class="section about", id="sponsors">
  <div class="row">
    <div class="medium-12 columns sponsors">
      <h3 class="">Our community sponsors:</h3>
      <ul class="small-block-grid-1 medium-block-grid-2">
        <li class="center">
          <%= image_tag "st_pauls_logo.png" %>
          <p class="">St. Paul's Episcopal Church</p>
          <p class="center">
            <%= link_to "http://www.stpaulsdekalb.org/", class: "social-links" do %>
              <%= fa_icon "home" %>
            <% end %>
            <%= link_to "https://www.facebook.com/pages/St-Pauls-Episcopal-Church-DeKalb-IL/115550275180279", class: "social-links" do %>
              <%= fa_icon "facebook" %>
            <% end %>
            <%= link_to "https://twitter.com/stpaulsdekalb", class: "social-links" do %>
              <%= fa_icon "twitter" %>
            <% end %>
          </p>
        </li>
        <li class="center">
          <%= image_tag "dccg_logo.png" %>
          <p class="">DeKalb County Community Gardens</p>
          <p class="center">
            <%= link_to "http://dekalbgardens.org/", class: "social-links" do %>
              <%= fa_icon "home" %>
            <% end %>
            <%= link_to "https://www.facebook.com/pages/DeKalb-County-Community-Gardens/172974836084982", class: "social-links" do %>
              <%= fa_icon "facebook" %>
            <% end %>
          </p>
        </li>
      </ul>
    </div>
  </div>
</div>
<%= render 'contact' %>