config/routes.rb
ThriveMarket::Application.routes.draw do

  root 'static_pages#home'

  get  "/home"               => "static_pages#home",     as: :home
  post "/phone_numbers"      => "phone_numbers#create"
  post  "webhooks/sms"       => 'webhooks#incoming_text'
  get  "/thanks"             => "static_pages#thanks",   as: :thanks
  post "survey_items/create" => 'survey_items#create',   as: :survey_items

  get    "admin/signin"  => "sessions#new",     as: :sign_in
  delete "admin/signout" => 'sessions#destroy', as: :sign_out

  resources :sessions, only: [ :create ]
  resources :updates,  only: [ :create, :destroy ]

  get "admin"               => "admin#index",         as: :admin
  get "admin/survey_items"  => "admin#survey_items",  as: :admin_survey_items
  get "admin/phone_numbers" => "admin#phone_numbers", as: :admin_phone_numbers
  get "admin/updates"       => "admin#updates",       as: :admin_updates

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <footer class="dark-black">
    <div class="row">
      <div class="medium-12 columns">
        <h6 class="light-gray center">
          Thrive Neighborhood Market & Community Garden<br>
          St. Paul's Episcopal Church<br>
          900 Normal Rd.<br>
          DeKalb, IL 60115<br>
          (815) 756‐4888<br>
          <%= link_to "info@thrivemarket.org", "mailto:info@thrivemarket.org" %>
        </h6>
        <div class="copyright center">
          <small class="light-gray">&copy; St. Paul's Episcopal Church 2014</small>
          <br>
          <small class="cc">
            Cultivating designed by Jerry Wang from the <%= link_to "Noun Project", "http://thenounproject.com/term/cultivating/38049/", class: "cc" %>,
          </small>
          <small class="cc">
            and hearts designed by Brandosaur.us from the <%= link_to "Noun Project", "http://thenounproject.com/term/hearts/31226/", class: "cc" %>
          </small>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% if notice.present? || alert.present? %>
  <div class="message-wrapper">
    <div class="row">
      <div class="medium-12 columns">
        <% if notice.present? %>
          <div data-alert class="alert-box success">
            <%= notice %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
        <% if alert.present? %>
          <div data-alert class="alert-box alert">
            <%= alert %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="contain-to-grid fixed" id="nav">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <%= link_to root_url do %>
          <%= image_tag 'thrive_logo_nav.svg', alt: "Thrive Logo", class: "top-bar-logo" %>
        <% end %>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li>
          <% if home? %>
            <%= link_to "ABOUT", "#about", class: "smooth" %>
          <% else %>
            <%= link_to "ABOUT", root_url(anchor: "about"), class: "smooth" %>
          <% end %>
        </li>
        <li>
          <% if home? %>
            <%= link_to "WHEN", "#when", class: "smooth" %>
          <% else %>
            <%= link_to "WHEN", root_url(anchor: "when"), class: "smooth" %>
          <% end %>
        </li>
        <li>
          <% if home? %>
            <%= link_to "SPONSORS", "#sponsors", class: "smooth" %>
          <% else %>
            <%= link_to "SPONSORS", root_url(anchor: "sponsors"), class: "smooth" %>
          <% end %>
        </li>
        <!-- <li>
          <%# if home? %>
            <%#= link_to "CONTACT", "#contact", class: "smooth" %>
          <%# else %>
            <%#= link_to "CONTACT", root_url(anchor: "contact"), class: "smooth" %>
          <%# end %>
        </li> -->
        <li><%= link_to "BLOG", "http://thrivemarket.tumblr.com/" %></li>
        <% if signed_in? %>
          <li><%= link_to "ADMIN", admin_url, class: "orange" %></li>
          <li><%= link_to "SIGN OUT", sign_out_url, method: "delete", class: "orange" %></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Thrive Neighborhood Market & Community Garden" %></title>
    <meta name="keywords" content="DeKalb, community garden, thrive, neighborhood market, Thrive Neighborhood Market & Community Garden, St. Paul's Episcopal Church" />
    <meta name="description" content="<%= content_for?(:desc) ? yield(:desc) : 'Cultivating community by growing affordable local produce and sharing ideas for healthy living.' %>" />
    <meta property="og:url" content="http://www.thrivemarket.org">
    <meta property="og:title" content="<%= content_for?(:title) ? yield(:title) : 'Thrive Neighborhood Market & Community Garden' %>">
    <meta property="og:description" content="<%= content_for?(:desc) ? yield(:desc) : 'Cultivating community by growing affordable local produce and sharing ideas for healthy living.' %>">
    <meta property="og:image" content="https://s3.amazonaws.com/thrivemarket.org/images/background_tumblr.jpg">
    <%= favicon_link_tag 'favicon.png', :rel => 'shortcut icon' %>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40057880-2', 'thrivemarket.org');
      ga('send', 'pageview');

    </script>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <% if params[:action] == "home" %>
      <%= yield %>
    <% else %>
      <div class="main-wrapper">
        <div class="row">
          <div class="medium-12 columns">
            <%= render 'layouts/messages' %>
          </div>
        </div>
        <%= yield %>
      </div>
    <% end %>

    <%= render 'layouts/footer' %>

    <%= javascript_include_tag "application" %>

  </body>
</html>